name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21']
    steps:
      - uses: actions/checkout@v4
      - name: setup go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
      - name: build linux
        run: |
          export CGO_ENABLED=0
          go version
          go env
          go test ./...
          go build -v .
          mkdir -p _dist/linux
          cp moni README.md _dist/linux
      - name: upload-linux
        uses: actions/upload-artifact@v4
        with:
          name: moni-linux
          path: _dist/linux
      - name: build windows
        run: |
          export CGO_ENABLED=0
          export GOOS=windows
          export GOARCH=amd64
          go version
          go env
          go build -v .
          mkdir -p _dist/windows
          cp moni README.md _dist/windows
      - name: upload-windows
        uses: actions/upload-artifact@v4
        with:
          name: moni-windows
          path: _dist/windows
