name: linux
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21','1.22','1.23']
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}
      - name: build
        run: |
          export CGO_ENABLED=0
          go version
          go env
          go test -v ./...
          go build -v .
